const actions = {
  IS_LOADING: "IS_LOADING",
  DELETE_IS_LOADING: "DELETE_IS_LOADING",
  SUBMIT_IS_LOADING: "SUBMIT_IS_LOADING",

  LOAD_POSTS_SUCCESS: "LOAD_POSTS_SUCCESS",
  LOAD_POSTS_FAILURE: "LOAD_POSTS_FAILURE",
  LOAD_POST_DETAIL_SUCCESS: "LOAD_POST_DETAIL_SUCCESS",
  LOAD_POST_DETAIL_FAILURE: "LOAD_POST_DETAIL_FAILURE",
  LOAD_POSTS_LIST_SUCCESS: "LOAD_POSTS_LIST_SUCCESS",
  LOAD_POSTS_LIST_FAILURE: "LOAD_POSTS_LIST_FAILURE",

  DELETE_POST_LIST: "DELETE_POST_LIST",
  DELETE_POST_LIST_SUCCESS: "DELETE_POST_LIST_SUCCESS",
  DELETE_POST_LIST_FAILURE: "DELETE_POST_LIST_FAILURE",

  LOAD_A_POST_SUCCESS: "LOAD_A_POST_SUCCESS",
  LOAD_A_POST_FAILURE: "LOAD_A_POST_FAILURE",

  SUBMIT_POST_SUCCESS: "SUBMIT_POST_SUCCESS",
  SUBMIT_POST_FAILURE: "SUBMIT_POST_FAILURE",

  UPDATE_POST: "UPDATE_POST",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAILURE: "UPDATE_POST_FAILURE",
};

export default actions;
